adapters:
   SGE:
      host: API_GATEWAY_URL/SGE
   SAF:
      host: API_GATEWAY_URL/SAF
   SFC:
      host: API_GATEWAY_URL/SAF
credentials:
   api-gateway:
      key: ABC1
      secret: ABC1
server:
   port: ${SERVICE_PORT:8080}
spring:
   profiles:
      active: ${SPRING_PROFILE:}