server:
   port: ${SERVICE_PORT:8082}
   compression:
      enabled: true
      mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/hal+json
      
spring:
   application:
      name: mercadoria-service
   profiles:
      active: ${SPRING_PROFILE:}
   jpa:
      properties:
         hibernate:
            format_sql: false
            batch_size: 50
            order_updates: true
            batch_versioned_data: true
      hibernate:
         ddl-auto: none
   liquibase:
      enabled: false
      
credentials:
   api-gateway:
      key: ABC1
      secret: ABC1
      
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true